apiVersion: v1
kind: Pod
metadata:
  name: postgres-fixdb
spec:
  volumes:
  - name: data-db
    persistentVolumeClaim:
      claimName: postgres-data-db
  containers:
  - image: postgres
    name: postgres-fixdb
    securityContext:
      runAsUser: 999
    args:
    - pg_resetwal
    - /var/lib/postgresql/data
    volumeMounts:
      - name: data-db
        mountPath: /var/lib/postgresql/data
        subPath: postgresdb
  restartPolicy: Never
