apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.appconfig.profile }}
  SERVER_PORT: {{ .Values.app.appconfig.httpport | quote }}
