apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: {{  .Values.app.dbconfig.jdbcurl | b64enc}}
  SPRING_DATASOURCE_USERNAME: {{  .Values.app.dbconfig.user | b64enc}}
  SPRING_DATASOURCE_PASSWORD: {{  .Values.app.dbconfig.password | b64enc}}
